import argparse
import os
import requests
import sys
from dotenv import load_dotenv
from google.adk.runners import Runner
from pr_review_agent.agent import root_agent

def fetch_pr_diff(repo: str, pr_number: str, token: str) -> str:
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3.diff"
    }
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Error fetching PR diff: {response.status_code}")
        print(response.text)
        sys.exit(1)
    return response.text

def post_pr_comment(repo: str, pr_number: str, token: str, comment_body: str):
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "body": comment_body
    }
    response = requests.post(url, headers=headers, json=data)
    if response.status_code != 201:
        print(f"Error posting PR comment: {response.status_code}")
        print(response.text)
        sys.exit(1)
    print("Successfully posted PR review comment!")

def main():
    parser = argparse.ArgumentParser(description="AI PR Review Bot")
    parser.add_argument("--repo", required=True, help="GitHub repository (e.g., owner/name)")
    parser.add_argument("--pr", required=True, help="Pull Request number")
    args = parser.parse_args()

    load_dotenv()
    
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        print("Error: GITHUB_TOKEN environment variable is not set.")
        sys.exit(1)
        
    google_api_key = os.getenv("GOOGLE_API_KEY")
    if not google_api_key:
        print("Error: GOOGLE_API_KEY environment variable is not set.")
        sys.exit(1)

    print(f"Fetching diff for PR #{args.pr} in {args.repo}...")
    pr_diff = fetch_pr_diff(args.repo, args.pr, github_token)
    
    if not pr_diff.strip():
        print("No changes found in the PR diff.")
        sys.exit(0)

    print("Analyzing PR diff with Gemini...")
    import asyncio
    from google.adk.sessions import InMemorySessionService
    from google.genai import types
    
    session_service = InMemorySessionService()
    try:
        asyncio.run(session_service.create_session(app_name="pr_review", user_id="cli_user", session_id="cli_session"))
    except Exception:
        pass # Ignore if it already exists or fails
        
    runner = Runner(agent=root_agent, session_service=session_service, app_name="pr_review")
    
    user_message = types.Content(role='user', parts=[types.Part(text=f"Please review this PR diff:\n\n{pr_diff}")])
    events = runner.run(user_id="cli_user", session_id="cli_session", new_message=user_message)
    
    review_comments = None
    for event in events:
        if hasattr(event, 'is_final_response') and event.is_final_response():
            if event.content and event.content.parts:
                review_comments = event.content.parts[0].text
                break
    
    if not review_comments:
        print("Error: Agent did not return any review comments.")
        sys.exit(1)

    print("Review generated. Posting comment to GitHub...")
    # Add a friendly prefix
    comment_body = f"## AI Code Review\n\n{review_comments}\n\n_Generated by AI PR Review Bot_"
    post_pr_comment(args.repo, args.pr, github_token, comment_body)

if __name__ == "__main__":
    main()
